package entity;
// Generated Mar 3, 2020 10:50:16 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * Depart generated by hbm2java
 */
public class Depart implements java.io.Serializable {

    private String departid;
    private String name;
    private Boolean status;
    private String photo;

    private Set<Staff> staffs = new HashSet<Staff>(0);

    public Depart() {
    }

    public Depart(String departid) {
        this.departid = departid;
    }

    public Depart(String departid, String name, Boolean status, String photo, Set<Staff> staffs) {
        this.departid = departid;
        this.name = name;
        this.status = status;
        this.photo = photo;
        this.staffs = staffs;
    }

    public String getDepartid() {
        return this.departid;
    }

    public void setDepartid(String departid) {
        this.departid = departid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public String getPhoto() {
        return this.photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public Set<Staff> getStaffs() {
        return this.staffs;
    }

    public void setStaffs(Set<Staff> staffs) {
        this.staffs = staffs;
    }
}
