package entity;
// Generated Mar 3, 2020 10:50:16 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;

/**
 * Record generated by hbm2java
 */
public class Record implements java.io.Serializable {

    private int recordid;
    private Staff staff;
    private Boolean type;
    private Date date;
    private String note;

    public Record() {
    }

    public Record(int recordid) {
        this.recordid = recordid;
    }

    public Record(int recordid, Staff staff, Boolean type, Date date, String note) {
        this.recordid = recordid;
        this.staff = staff;
        this.type = type;
        this.date = date;
        this.note = note;
    }

    public int getRecordid() {
        return this.recordid;
    }

    public void setRecordid(int recordid) {
        this.recordid = recordid;
    }

    public Staff getStaff() {
        return this.staff;
    }

    public void setStaff(Staff staff) {
        this.staff = staff;
    }

    public Boolean getType() {
        return this.type;
    }

    public void setType(Boolean type) {
        this.type = type;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

}
