package entity;
// Generated Mar 3, 2020 10:50:16 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Staff generated by hbm2java
 */
public class Staff implements java.io.Serializable {

    private int staffid;
    private Depart depart;
    private String name;
    private Boolean gender;
    private Date birthday;
    private String email;
    private Double salary;
    private String photo;
    private String notes;
    private Boolean deleted;
    private Set<Record> records = new HashSet<Record>(0);

    public Staff() {
    }

    public Staff(int staffid) {
        this.staffid = staffid;
    }

    public Staff(int staffid, Depart depart, String name, Boolean gender, Date birthday, String email, Double salary, String photo, String notes, Boolean deleted, Set<Record> records) {
        this.staffid = staffid;
        this.depart = depart;
        this.name = name;
        this.gender = gender;
        this.birthday = birthday;
        this.email = email;
        this.salary = salary;
        this.photo = photo;
        this.notes = notes;
        this.deleted = deleted;
        this.records = records;
    }

    public int getStaffid() {
        return this.staffid;
    }

    public void setStaffid(int staffid) {
        this.staffid = staffid;
    }

    public Depart getDepart() {
        return this.depart;
    }

    public void setDepart(Depart depart) {
        this.depart = depart;
    }

    public Serializable getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getGender() {
        return this.gender;
    }

    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    public Date getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Double getSalary() {
        return this.salary;
    }

    public void setSalary(Double salary) {
        this.salary = salary;
    }

    public String getPhoto() {
        return this.photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public Serializable getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Boolean getDeleted() {
        return this.deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    public Set<Record> getRecords() {
        return this.records;
    }

    public void setRecords(Set<Record> records) {
        this.records = records;
    }

}
