package entity;
// Generated Mar 3, 2020 10:50:16 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.lang.reflect.Field;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import util.Validate;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

    private String username;
    private String password;
    private String fullname;
    private String image;

    public Users() {
    }

    public Users(String username) {
        this.username = username;
    }

    public Users(String username, String password, String fullname, String image) {
        this.username = username;
        this.password = password;
        this.fullname = fullname;
        this.image = image;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFullname() {
        return this.fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    @Override
    public String toString() {
        return "Users{" + "username=" + username + ", password=" + password + ", fullname=" + fullname + ", image=" + image + '}';
    }

   
}
